export const LIST_ADD = "LIST_ADD"
export const LIST_REMOVE = "LIST_REMOVE"

export const LIST_ADD_DONE = "LIST_ADD_DONE"
export const LIST_REMOVE_DONE = "LIST_REMOVE_DONE"
export const  LIST_UPDATE_TODO = "LIST_UPDATE_TODO"
export const  LIST_DELETE_ALL = "LIST_DELETE_ALL"
export const LIST_EDIT_TODO = "LIST_EDIT_TODO"
